### ISSUE TITLE
Server-side Istio resources created in default namespace

### ISSUE THREAD

**Issue by esnible** [istio-ecosystem/wharf-multicluster-sync#29]
To reproduce, create a non-default ServiceExpositionPolicy

```
apiVersion: multicluster.istio.io/v1alpha1
kind: ServiceExpositionPolicy
metadata:
  annotations:
  name: ratings
  namespace: bookinfo
spec:
  exposed:
  - name: ratings
    port: 9080
```

Run the CLI tool:
mc-tool --filename /tmp/ratings_sep.yaml --mc-conf-filename /tmp/mc-config.yaml 

The stdout Istio config will be in the default, not bookinfo, namespace.
