### ISSUE TITLE
Tutorial agents fail with "Peer agent [cluster2] is not accessible. response status code is not OK"

### ISSUE THREAD

**Issue by esnible** [istio-ecosystem/wharf-multicluster-sync#8]
The agents are running servers, and the servers do what is expected:

```
kubectl --context $CLUSTER2 -n istio-system exec -it mc-agent-6b5cd56595-5gcxc -- wget -O - mc-agent.istio-system.svc.cluster.local:8999/exposed/cluster1
```

However the services are not exposed to the outside.  I get 503s

```
curl  169.62.214.226:80/exposed/cluster1
upstream connect error or disconnect/reset before headers
```

The error is 503.

I see a VirtualService directing `/exposed` to mc-agent.istio-system.svc.cluster.local port 8999 so I don't know what is going wrong.

**Comment by ymesika** [comment]
I can't reproduce it with two clusters. Both of them have Istio v1.0.2 installed.

I ran the following commands:
```sh
deploy_cluster.sh cluster2=my_context2
deploy_cluster.sh cluster1=my_context1 cluster2=my_context2
```

And the agent from cluster1 connects without any problems to the one on cluster2.

**Comment by esnible** [comment]
@ymesika We have mTLS configured.  The problem goes away if we create DestinationRule for mc-agent like this:

```
cat <<EOF | kubectl --context $CLUSTER3 apply -n istio-system -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: mc-agent
spec:
 host: mc-agent.istio-system.svc.cluster.local
 trafficPolicy:
   tls:
     mode: DISABLE
EOF
```

I could fix this by having _deploy_cluster.sh_ create that rule.  Is it reasonable, for the demo, that we configure no security between the ingressgateway and mc-agent?
